# Generated by Django 4.2.2 on 2023-06-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='device_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
